import { MeasurementUnits } from './MeasurementUnits';

export type HabitCategory = 'physical' | 'mental' | 'emotional' | 'spiritual';

export interface HabitTemplate {
  id: string;
  name: string;
  description: string;
  category: HabitCategory;
  frequency: 'daily' | 'weekly';
  goalType: 'completion' | 'duration' | 'count' | 'time';
  defaultGoalValue?: number;
  defaultGoalUnit?: string;
  icon: string;
  color?: string;
}

export const CATEGORIES = [
  {
    id: 'physical',
    name: 'Physical',
    icon: '💪',
    description: 'Physical health and wellbeing',
    color: '#FF6B6B',
  },
  {
    id: 'mental',
    name: 'Mental',
    icon: '🧠',
    description: 'Mental acuity and cognitive development',
    color: '#4ECDC4',
  },
  {
    id: 'emotional',
    name: 'Emotional',
    icon: '❤️',
    description: 'Emotional wellbeing and relationships',
    color: '#D4A5A5',
  },
  {
    id: 'spiritual',
    name: 'Spiritual',
    icon: '✨',
    description: 'Purpose, meaning, and values',
    color: '#9B59B6',
  },
];

export const HABIT_TEMPLATES: HabitTemplate[] = [
  // Physical Habits
  {
    id: 'exercise',
    name: 'Exercise',
    description: 'Stay active with regular physical activity',
    category: 'physical',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 30,
    defaultGoalUnit: 'min',
    icon: '🏃‍♂️',
    color: '#FF6B6B',
  },
  {
    id: 'drink_water',
    name: 'Drink Water',
    description: 'Stay hydrated throughout the day',
    category: 'physical',
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 8,
    defaultGoalUnit: 'glasses',
    icon: '💧',
    color: '#45B7D1',
  },
  {
    id: 'sleep_early',
    name: 'Sleep Early',
    description: 'Get to bed by a consistent time',
    category: 'physical',
    frequency: 'daily',
    goalType: 'time',
    icon: '😴',
    color: '#9B59B6',
  },
  {
    id: 'vitamins',
    name: 'Take Vitamins',
    description: 'Remember daily supplements',
    category: 'physical',
    frequency: 'daily',
    goalType: 'completion',
    icon: '💊',
    color: '#96CEB4',
  },
  {
    id: 'healthy_meal',
    name: 'Eat Healthy Meal',
    description: 'Focus on nutritious food choices',
    category: 'physical',
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 3,
    icon: '🥗',
    color: '#FFEEAD',
  },

  // Mental Habits
  {
    id: 'read',
    name: 'Read',
    description: 'Expand your mind through reading',
    category: 'mental',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 20,
    defaultGoalUnit: 'min',
    icon: '📚',
    color: '#4ECDC4',
  },
  {
    id: 'learn_skill',
    name: 'Learn New Skill',
    description: 'Dedicate time to learning something new',
    category: 'mental',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 15,
    defaultGoalUnit: 'min',
    icon: '🎯',
    color: '#FF6B6B',
  },
  {
    id: 'limit_social',
    name: 'Limit Social Media',
    description: 'Reduce time spent on social platforms',
    category: 'mental',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 30,
    defaultGoalUnit: 'min',
    icon: '📱',
    color: '#D4A5A5',
  },
  {
    id: 'puzzles',
    name: 'Brain Puzzles',
    description: 'Keep your mind sharp with puzzles',
    category: 'mental',
    frequency: 'daily',
    goalType: 'completion',
    icon: '🧩',
    color: '#3498DB',
  },
  {
    id: 'language',
    name: 'Language Practice',
    description: 'Practice a new language',
    category: 'mental',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 10,
    defaultGoalUnit: 'min',
    icon: '🗣️',
    color: '#45B7D1',
  },

  // Emotional Habits
  {
    id: 'gratitude',
    name: 'Gratitude Journal',
    description: "Write down things you're grateful for",
    category: 'emotional',
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 3,
    defaultGoalUnit: 'items',
    icon: '🙏',
    color: '#D4A5A5',
  },
  {
    id: 'connect',
    name: 'Connect with Someone',
    description: 'Reach out to a friend or family member',
    category: 'emotional',
    frequency: 'daily',
    goalType: 'completion',
    icon: '👋',
    color: '#FF6B6B',
  },
  {
    id: 'self_care',
    name: 'Self-Care Time',
    description: 'Take time for yourself',
    category: 'emotional',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 15,
    defaultGoalUnit: 'min',
    icon: '🛀',
    color: '#96CEB4',
  },
  {
    id: 'no_complaining',
    name: 'No Complaining',
    description: 'Practice positive speech',
    category: 'emotional',
    frequency: 'daily',
    goalType: 'completion',
    icon: '😊',
    color: '#FFEEAD',
  },
  {
    id: 'kindness',
    name: 'Act of Kindness',
    description: 'Do something nice for someone else',
    category: 'emotional',
    frequency: 'daily',
    goalType: 'completion',
    icon: '❤️',
    color: '#D4A5A5',
  },

  // Spiritual Habits
  {
    id: 'meditation',
    name: 'Meditation',
    description: 'Clear your mind and be present',
    category: 'spiritual',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 10,
    defaultGoalUnit: 'min',
    icon: '🧘‍♀️',
    color: '#9B59B6',
  },
  {
    id: 'nature',
    name: 'Nature Time',
    description: 'Spend time in nature',
    category: 'spiritual',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 20,
    defaultGoalUnit: 'min',
    icon: '🌳',
    color: '#96CEB4',
  },
  {
    id: 'reflection',
    name: 'Reflection',
    description: 'Reflect on your day and growth',
    category: 'spiritual',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 5,
    defaultGoalUnit: 'min',
    icon: '💭',
    color: '#3498DB',
  },
  {
    id: 'affirmations',
    name: 'Affirmations',
    description: 'Practice positive self-talk',
    category: 'spiritual',
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 3,
    icon: '✅',
    color: '#4ECDC4',
  },
  {
    id: 'digital_sunset',
    name: 'Digital Sunset',
    description: 'No screens before bed',
    category: 'spiritual',
    frequency: 'daily',
    goalType: 'time',
    icon: '🌙',
    color: '#9B59B6',
  },
];
