import { MeasurementUnits } from './MeasurementUnits';

export const CATEGORY_IDS = [
  'body',
  'mind',
  'heart',
  'spirit',
  'work',
] as const;
export type HabitCategory = (typeof CATEGORY_IDS)[number];

export interface HabitTemplate {
  id: string;
  name: string;
  description: string;
  category: HabitCategory;
  frequency: 'daily' | 'weekly';
  goalType: 'completion' | 'duration' | 'count' | 'time';
  defaultGoalValue?: number;
  defaultGoalUnit?: string;
  icon: string;
  color?: string;
}

export const CATEGORIES = [
  {
    id: 'body',
    name: 'Body',
    icon: '💪',
    description: 'Physical health and wellbeing',
    color: '#FF5E5B',
  },
  {
    id: 'mind',
    name: 'Mind',
    icon: '🧠',
    description: 'Mental clarity and focus',
    color: '#5E97F7',
  },
  {
    id: 'heart',
    name: 'Heart',
    icon: '❤️',
    description: 'Emotional well-being',
    color: '#FF9AA2',
  },
  {
    id: 'spirit',
    name: 'Spirit',
    icon: '✨',
    description: 'Spiritual fulfillment',
    color: '#A78BFA',
  },
  {
    id: 'work',
    name: 'Work',
    icon: '💼',
    description: 'Professional growth',
    color: '#5BBAA9',
  },
] as const;

export const HABIT_TEMPLATES: HabitTemplate[] = [
  // Body Habits
  {
    id: 'exercise',
    name: 'Exercise',
    description: 'Stay active with regular physical activity',
    category: CATEGORIES[0].id,
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 30,
    defaultGoalUnit: 'min',
    icon: '🏃‍♂️',
    color: '#FF6B6B',
  },
  {
    id: 'drink_water',
    name: 'Drink Water',
    description: 'Stay hydrated throughout the day',
    category: CATEGORIES[0].id,
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 8,
    defaultGoalUnit: 'glasses',
    icon: '💧',
    color: '#45B7D1',
  },
  {
    id: 'sleep_early',
    name: 'Sleep Early',
    description: 'Get to bed by a consistent time',
    category: CATEGORIES[0].id,
    frequency: 'daily',
    goalType: 'time',
    icon: '😴',
    color: '#9B59B6',
  },
  {
    id: 'vitamins',
    name: 'Take Vitamins',
    description: 'Remember daily supplements',
    category: CATEGORIES[0].id,
    frequency: 'daily',
    goalType: 'completion',
    icon: '💊',
    color: '#96CEB4',
  },
  {
    id: 'healthy_meal',
    name: 'Eat Healthy Meal',
    description: 'Focus on nutritious food choices',
    category: CATEGORIES[0].id,
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 3,
    icon: '🥗',
    color: '#FFEEAD',
  },

  // Mind Habits
  {
    id: 'read',
    name: 'Read',
    description: 'Expand your mind through reading',
    category: CATEGORIES[1].id,
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 20,
    defaultGoalUnit: 'min',
    icon: '📚',
    color: '#4ECDC4',
  },
  {
    id: 'learn_skill',
    name: 'Learn New Skill',
    description: 'Dedicate time to learning something new',
    category: CATEGORIES[1].id,
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 15,
    defaultGoalUnit: 'min',
    icon: '🎯',
    color: '#FF6B6B',
  },
  {
    id: 'brain_training',
    name: 'Brain Training',
    description: 'Keep your mind sharp with puzzles or challenges',
    category: CATEGORIES[1].id,
    frequency: 'daily',
    goalType: 'completion',
    icon: '🧩',
    color: '#3498DB',
  },
  {
    id: 'language',
    name: 'Language Practice',
    description: 'Practice a new language',
    category: CATEGORIES[1].id,
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 10,
    defaultGoalUnit: 'min',
    icon: '🗣️',
    color: '#45B7D1',
  },
  {
    id: 'digital_detox',
    name: 'Digital Detox',
    description: 'Limit social media and screen time',
    category: CATEGORIES[1].id,
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 30,
    defaultGoalUnit: 'min',
    icon: '📱',
    color: '#D4A5A5',
  },

  // Heart Habits
  {
    id: 'connect',
    name: 'Connect with Someone',
    description: 'Reach out to a friend or family member',
    category: CATEGORIES[2].id,
    frequency: 'daily',
    goalType: 'completion',
    icon: '👋',
    color: '#FF6B6B',
  },
  {
    id: 'quality_time',
    name: 'Quality Time',
    description: 'Spend meaningful time with loved ones',
    category: CATEGORIES[2].id,
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 30,
    defaultGoalUnit: 'min',
    icon: '💝',
    color: '#D4A5A5',
  },
  {
    id: 'kindness',
    name: 'Acts of Kindness',
    description: 'Do something nice for others',
    category: CATEGORIES[2].id,
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 1,
    defaultGoalUnit: 'act',
    icon: '🤝',
    color: '#96CEB4',
  },
  {
    id: 'gratitude',
    name: 'Express Gratitude',
    description: 'Share appreciation with others',
    category: CATEGORIES[2].id,
    frequency: 'daily',
    goalType: 'completion',
    icon: '🙏',
    color: '#FFEEAD',
  },
  {
    id: 'active_listening',
    name: 'Active Listening',
    description: 'Practice being fully present in conversations',
    category: CATEGORIES[2].id,
    frequency: 'daily',
    goalType: 'completion',
    icon: '👂',
    color: '#D4A5A5',
  },

  // Spirit Habits
  {
    id: 'meditation',
    name: 'Meditation',
    description: 'Clear your mind and be present',
    category: CATEGORIES[3].id,
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 10,
    defaultGoalUnit: 'min',
    icon: '🧘‍♀️',
    color: '#9B59B6',
  },
  {
    id: 'journal',
    name: 'Journal',
    description: 'Reflect on your thoughts and feelings',
    category: CATEGORIES[3].id,
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 10,
    defaultGoalUnit: 'min',
    icon: '📔',
    color: '#4ECDC4',
  },
  {
    id: 'nature',
    name: 'Nature Time',
    description: 'Spend time in nature',
    category: CATEGORIES[3].id,
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 20,
    defaultGoalUnit: 'min',
    icon: '🌳',
    color: '#96CEB4',
  },
  {
    id: 'affirmations',
    name: 'Affirmations',
    description: 'Practice positive self-talk',
    category: CATEGORIES[3].id,
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 3,
    icon: '✨',
    color: '#FFEEAD',
  },
  {
    id: 'mindful_break',
    name: 'Mindful Break',
    description: 'Take mindful pauses throughout the day',
    category: CATEGORIES[3].id,
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 3,
    icon: '🌅',
    color: '#9B59B6',
  },

  // Work Habits
  {
    id: 'priority_task',
    name: 'Priority Task',
    description: 'Complete your most important task first',
    category: CATEGORIES[4].id,
    frequency: 'daily',
    goalType: 'completion',
    icon: '⭐',
    color: '#3498DB',
  },
  {
    id: 'time_blocking',
    name: 'Time Blocking',
    description: 'Schedule focused work periods',
    category: CATEGORIES[4].id,
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 90,
    defaultGoalUnit: 'min',
    icon: '⏰',
    color: '#FF6B6B',
  },
  {
    id: 'inbox_zero',
    name: 'Inbox Zero',
    description: 'Process and organize emails',
    category: CATEGORIES[4].id,
    frequency: 'daily',
    goalType: 'completion',
    icon: '📧',
    color: '#4ECDC4',
  },
  {
    id: 'skill_development',
    name: 'Skill Development',
    description: 'Work on professional skills',
    category: CATEGORIES[4].id,
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 20,
    defaultGoalUnit: 'min',
    icon: '📈',
    color: '#96CEB4',
  },
  {
    id: 'plan_tomorrow',
    name: 'Plan Tomorrow',
    description: 'Set goals and priorities for next day',
    category: CATEGORIES[4].id,
    frequency: 'daily',
    goalType: 'completion',
    icon: '📋',
    color: '#D4A5A5',
  },
];
