import { IconType } from './icons';
import { MeasurementUnits } from './MeasurementUnits';

export const CATEGORY_IDS = ['cat1', 'cat2', 'cat3', 'cat4', 'cat5'] as const;

export type HabitCategory = (typeof CATEGORY_IDS)[number];
export interface HabitTemplate {
  id: string;
  name: string;
  description: string;
  nameKey: string;
  descriptionKey: string;
  category: HabitCategory;
  frequency: 'daily';
  goalType: 'completion' | 'duration' | 'count' | 'time';
  defaultGoalValue?: number;
  defaultGoalUnit?: keyof typeof MeasurementUnits;
  icon: IconType;
  color: string;
  type: 'GOOD' | 'BAD';
}

export const CATEGORIES = [
  {
    id: 'cat1',
    name: 'Vitality',
    icon: require('@/assets/icons/vitality.png'),
    description: 'Physical health and energy',
    color: '#FF6B6B',
    display: {
      title: '#E47980',
      number: '#F94B54',
      background: '#FFE2E1',
    },
  },
  {
    id: 'cat2',
    name: 'Wisdom',
    icon: require('@/assets/icons/wisdom.png'),
    description: 'Mental growth and learning',
    color: '#4A90E2',
    display: {
      title: '#5D92F2',
      number: '#4984ED',
      background: '#DDE7F8',
    },
  },
  {
    id: 'cat3',
    name: 'Harmony',
    icon: require('@/assets/icons/harmony.png'),
    description: 'Balance and relationships',
    color: '#7ED6A7',
    display: {
      title: '#E47980',
      number: '#FB919F',
      background: '#FEEBED',
    },
  },
  {
    id: 'cat4',
    name: 'Spirit',
    icon: require('@/assets/icons/spirit.png'),
    description: 'Inner peace and mindfulness',
    color: '#A974F8',
    display: {
      title: '#9D8DD3',
      number: '#9680E1',
      background: '#F0EBFD',
    },
  },
  {
    id: 'cat5',
    name: 'Ambition',
    icon: require('@/assets/icons/ambition.png'),
    description: 'Career and personal goals',
    color: '#FFA726',
    display: {
      title: '#75BBA8',
      number: '#44AF99',
      background: '#DEF3EE',
    },
  },
] as const;

export const TOTAL_CATEGORY = {
  id: 'total',
  name: 'Total',
  icon: require('@/assets/icons/ambition.png'),
  description: 'Overall life balance',
  color: '#FFA726',
  display: {
    title: '#F6B52F',
    number: '#F6B52F',
    background: '#FEF4D3',
  },
} as const;

// categories map
export const CATEGORIES_MAP = CATEGORIES.reduce((acc, category) => {
  acc[category.id] = category;
  return acc;
}, {} as Record<HabitCategory, (typeof CATEGORIES)[number]>);

export const HABIT_TEMPLATES: HabitTemplate[] = [
  /* ──────────── VITALITY ──────────── */
  {
    id: 'vitality_good_1',
    name: 'Daily Exercise',
    description: 'Get at least 30 minutes of moderate-intensity exercise.',
    nameKey: 'habitTemplates.vitality_good_1.name',
    descriptionKey: 'habitTemplates.vitality_good_1.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 30,
    defaultGoalUnit: 'minutes',
    icon: 'fitness-center',
    color: '#66BB6A',
    type: 'GOOD',
  },
  {
    id: 'vitality_good_2',
    name: 'Drink Water',
    description: 'Drink at least 8 glasses of water.',
    nameKey: 'habitTemplates.vitality_good_2.name',
    descriptionKey: 'habitTemplates.vitality_good_2.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 8,
    defaultGoalUnit: 'glasses',
    icon: 'local-drink',
    color: '#59B0F6',
    type: 'GOOD',
  },
  {
    id: 'vitality_good_3',
    name: 'Fruits & Vegetables',
    description: 'Eat at least 5 servings of fruits and vegetables.',
    nameKey: 'habitTemplates.vitality_good_3.name',
    descriptionKey: 'habitTemplates.vitality_good_3.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 5,
    defaultGoalUnit: 'servings',
    icon: 'local-dining',
    color: '#81C784',
    type: 'GOOD',
  },
  {
    id: 'vitality_good_4',
    name: '7+ Hours Sleep',
    description: 'Sleep at least 7 hours each night.',
    nameKey: 'habitTemplates.vitality_good_4.name',
    descriptionKey: 'habitTemplates.vitality_good_4.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 7,
    defaultGoalUnit: 'hours',
    icon: 'hotel-class',
    color: '#5C6BC0',
    type: 'GOOD',
  },
  {
    id: 'vitality_good_5',
    name: 'Daily Stretching',
    description: 'Stretch for 10 minutes.',
    nameKey: 'habitTemplates.vitality_good_5.name',
    descriptionKey: 'habitTemplates.vitality_good_5.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 10,
    defaultGoalUnit: 'minutes',
    icon: 'accessibility-new',
    color: '#26A69A',
    type: 'GOOD',
  },
  {
    id: 'vitality_good_6',
    name: 'Take Vitamins',
    description: 'Take prescribed vitamins or supplements.',
    nameKey: 'habitTemplates.vitality_good_6.name',
    descriptionKey: 'habitTemplates.vitality_good_6.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'medical-services',
    color: '#FFB300',
    type: 'GOOD',
  },
  {
    id: 'vitality_good_7',
    name: 'Healthy Breakfast',
    description: 'Eat a balanced breakfast to start the day.',
    nameKey: 'habitTemplates.vitality_good_7.name',
    descriptionKey: 'habitTemplates.vitality_good_7.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'free-breakfast',
    color: '#FFF176',
    type: 'GOOD',
  },
  {
    id: 'vitality_good_8',
    name: 'Walk 8 000 Steps',
    description: 'Reach at least 8 000 steps by the end of the day.',
    nameKey: 'habitTemplates.vitality_good_8.name',
    descriptionKey: 'habitTemplates.vitality_good_8.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 8000,
    defaultGoalUnit: 'steps',
    icon: 'directions-walk',
    color: '#4FC3F7',
    type: 'GOOD',
  },
  {
    id: 'vitality_good_9',
    name: 'Floss Teeth',
    description: 'Floss to maintain dental hygiene.',
    nameKey: 'habitTemplates.vitality_good_9.name',
    descriptionKey: 'habitTemplates.vitality_good_9.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'tag-faces',
    color: '#F48FB1',
    type: 'GOOD',
  },
  {
    id: 'vitality_good_10',
    name: 'Skincare Routine',
    description: 'Complete your daily skincare routine.',
    nameKey: 'habitTemplates.vitality_good_10.name',
    descriptionKey: 'habitTemplates.vitality_good_10.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'spa',
    color: '#7E57C2',
    type: 'GOOD',
  },

  {
    id: 'vitality_bad_1',
    name: 'Junk Food',
    description: 'Ate junk food or sugary snacks.',
    nameKey: 'habitTemplates.vitality_bad_1.name',
    descriptionKey: 'habitTemplates.vitality_bad_1.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'fastfood',
    color: '#FF8A65',
    type: 'BAD',
  },
  {
    id: 'vitality_bad_2',
    name: 'Sugary Drinks',
    description: 'Consumed soda or other sugary drinks.',
    nameKey: 'habitTemplates.vitality_bad_2.name',
    descriptionKey: 'habitTemplates.vitality_bad_2.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'emoji-food-beverage',
    color: '#FFB74D',
    type: 'BAD',
  },
  {
    id: 'vitality_bad_3',
    name: 'Smoking',
    description: 'Smoked any cigarettes or vapes.',
    nameKey: 'habitTemplates.vitality_bad_3.name',
    descriptionKey: 'habitTemplates.vitality_bad_3.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'smoking-rooms',
    color: '#EF5350',
    type: 'BAD',
  },
  {
    id: 'vitality_bad_4',
    name: 'Excess Screen-Time',
    description: 'Spent excessive leisure time on screens.',
    nameKey: 'habitTemplates.vitality_bad_4.name',
    descriptionKey: 'habitTemplates.vitality_bad_4.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'phone-android',
    color: '#00BCD4',
    type: 'BAD',
  },
  {
    id: 'vitality_bad_5',
    name: 'Late-Night Snacking',
    description: 'Snacked on food after 10 PM.',
    nameKey: 'habitTemplates.vitality_bad_5.name',
    descriptionKey: 'habitTemplates.vitality_bad_5.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'icecream',
    color: '#FFB300',
    type: 'BAD',
  },
  {
    id: 'vitality_bad_6',
    name: 'Hit Snooze',
    description: 'Hit the snooze button and overslept.',
    nameKey: 'habitTemplates.vitality_bad_6.name',
    descriptionKey: 'habitTemplates.vitality_bad_6.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'snooze',
    color: '#FFF176',
    type: 'BAD',
  },
  {
    id: 'vitality_bad_7',
    name: 'Alcohol Consumption',
    description: 'Drank alcoholic beverages.',
    nameKey: 'habitTemplates.vitality_bad_7.name',
    descriptionKey: 'habitTemplates.vitality_bad_7.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'local-bar',
    color: '#BA68C8',
    type: 'BAD',
  },
  {
    id: 'vitality_bad_8',
    name: 'Excess Caffeine',
    description: 'Had more than two caffeinated drinks.',
    nameKey: 'habitTemplates.vitality_bad_8.name',
    descriptionKey: 'habitTemplates.vitality_bad_8.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'local-cafe',
    color: '#F48FB1',
    type: 'BAD',
  },
  {
    id: 'vitality_bad_9',
    name: 'Late Bedtime',
    description: 'Went to bed after midnight.',
    nameKey: 'habitTemplates.vitality_bad_9.name',
    descriptionKey: 'habitTemplates.vitality_bad_9.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'nights-stay',
    color: '#7E57C2',
    type: 'BAD',
  },
  {
    id: 'vitality_bad_10',
    name: 'No Exercise',
    description: 'Did not perform any intentional exercise.',
    nameKey: 'habitTemplates.vitality_bad_10.name',
    descriptionKey: 'habitTemplates.vitality_bad_10.description',
    category: 'cat1',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'airline-seat-recline-normal',
    color: '#4FC3F7',
    type: 'BAD',
  },

  /* ──────────── WISDOM ──────────── */
  {
    id: 'wisdom_good_1',
    name: 'Reading',
    description: 'Read for 30 minutes.',
    nameKey: 'habitTemplates.wisdom_good_1.name',
    descriptionKey: 'habitTemplates.wisdom_good_1.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 30,
    defaultGoalUnit: 'minutes',
    icon: 'menu-book',
    color: '#7E57C2',
    type: 'GOOD',
  },
  {
    id: 'wisdom_good_2',
    name: 'Language Practice',
    description: 'Practice a foreign language for 15 minutes.',
    nameKey: 'habitTemplates.wisdom_good_2.name',
    descriptionKey: 'habitTemplates.wisdom_good_2.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 15,
    defaultGoalUnit: 'minutes',
    icon: 'language',
    color: '#5C6BC0',
    type: 'GOOD',
  },
  {
    id: 'wisdom_good_3',
    name: 'Practice Instrument',
    description: 'Play a musical instrument for 20 minutes.',
    nameKey: 'habitTemplates.wisdom_good_3.name',
    descriptionKey: 'habitTemplates.wisdom_good_3.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 20,
    defaultGoalUnit: 'minutes',
    icon: 'music-note',
    color: '#F48FB1',
    type: 'GOOD',
  },
  {
    id: 'wisdom_good_4',
    name: 'Puzzle Solving',
    description: 'Solve a puzzle or brain-teaser.',
    nameKey: 'habitTemplates.wisdom_good_4.name',
    descriptionKey: 'habitTemplates.wisdom_good_4.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'extension',
    color: '#FFF176',
    type: 'GOOD',
  },
  {
    id: 'wisdom_good_5',
    name: 'Learn Something New',
    description: 'Discover a new fact or concept.',
    nameKey: 'habitTemplates.wisdom_good_5.name',
    descriptionKey: 'habitTemplates.wisdom_good_5.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'lightbulb',
    color: '#FFB300',
    type: 'GOOD',
  },
  {
    id: 'wisdom_good_6',
    name: 'Online Course',
    description: 'Spend 20 minutes on an online course.',
    nameKey: 'habitTemplates.wisdom_good_6.name',
    descriptionKey: 'habitTemplates.wisdom_good_6.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 20,
    defaultGoalUnit: 'minutes',
    icon: 'school',
    color: '#BA68C8',
    type: 'GOOD',
  },
  {
    id: 'wisdom_good_7',
    name: 'Writing Practice',
    description: 'Write 500 words to improve writing skills.',
    nameKey: 'habitTemplates.wisdom_good_7.name',
    descriptionKey: 'habitTemplates.wisdom_good_7.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 500,
    defaultGoalUnit: 'words',
    icon: 'edit',
    color: '#59B0F6',
    type: 'GOOD',
  },
  {
    id: 'wisdom_good_8',
    name: 'Flashcard Review',
    description: 'Review your flashcards.',
    nameKey: 'habitTemplates.wisdom_good_8.name',
    descriptionKey: 'habitTemplates.wisdom_good_8.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'quiz',
    color: '#00BCD4',
    type: 'GOOD',
  },
  {
    id: 'wisdom_good_9',
    name: 'Read News',
    description: 'Read or watch reputable news sources.',
    nameKey: 'habitTemplates.wisdom_good_9.name',
    descriptionKey: 'habitTemplates.wisdom_good_9.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'public',
    color: '#4FC3F7',
    type: 'GOOD',
  },
  {
    id: 'wisdom_good_10',
    name: 'Learn a New Word',
    description: 'Add one new vocabulary word to your lexicon.',
    nameKey: 'habitTemplates.wisdom_good_10.name',
    descriptionKey: 'habitTemplates.wisdom_good_10.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'spellcheck',
    color: '#81C784',
    type: 'GOOD',
  },

  {
    id: 'wisdom_bad_1',
    name: 'Mindless Scrolling',
    description: 'Mindlessly scrolled social media.',
    nameKey: 'habitTemplates.wisdom_bad_1.name',
    descriptionKey: 'habitTemplates.wisdom_bad_1.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'phone-iphone',
    color: '#FF8A65',
    type: 'BAD',
  },
  {
    id: 'wisdom_bad_2',
    name: 'Binge Watching',
    description: 'Binge-watched TV shows or videos.',
    nameKey: 'habitTemplates.wisdom_bad_2.name',
    descriptionKey: 'habitTemplates.wisdom_bad_2.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'tv',
    color: '#FFB74D',
    type: 'BAD',
  },
  {
    id: 'wisdom_bad_3',
    name: 'Excessive Gaming',
    description: 'Played video games for an excessive period.',
    nameKey: 'habitTemplates.wisdom_bad_3.name',
    descriptionKey: 'habitTemplates.wisdom_bad_3.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'sports-esports',
    color: '#FFB300',
    type: 'BAD',
  },
  {
    id: 'wisdom_bad_4',
    name: 'Skipped Studying',
    description: 'Skipped planned study or practice.',
    nameKey: 'habitTemplates.wisdom_bad_4.name',
    descriptionKey: 'habitTemplates.wisdom_bad_4.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'library-books',
    color: '#EF5350',
    type: 'BAD',
  },
  {
    id: 'wisdom_bad_5',
    name: 'Clickbait Reading',
    description: 'Read clickbait or gossip articles.',
    nameKey: 'habitTemplates.wisdom_bad_5.name',
    descriptionKey: 'habitTemplates.wisdom_bad_5.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'article',
    color: '#00BCD4',
    type: 'BAD',
  },
  {
    id: 'wisdom_bad_6',
    name: 'Doomscrolling',
    description: 'Excessively consumed negative news.',
    nameKey: 'habitTemplates.wisdom_bad_6.name',
    descriptionKey: 'habitTemplates.wisdom_bad_6.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'rss-feed',
    color: '#7E57C2',
    type: 'BAD',
  },
  {
    id: 'wisdom_bad_7',
    name: 'Skipped Online Class',
    description: 'Skipped an online lesson or course.',
    nameKey: 'habitTemplates.wisdom_bad_7.name',
    descriptionKey: 'habitTemplates.wisdom_bad_7.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'laptop-chromebook',
    color: '#F48FB1',
    type: 'BAD',
  },
  {
    id: 'wisdom_bad_8',
    name: 'Aimless Web Surfing',
    description: 'Browsed the internet aimlessly.',
    nameKey: 'habitTemplates.wisdom_bad_8.name',
    descriptionKey: 'habitTemplates.wisdom_bad_8.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'search',
    color: '#4FC3F7',
    type: 'BAD',
  },
  {
    id: 'wisdom_bad_9',
    name: 'Comment Section Rabbit Hole',
    description: 'Got pulled into toxic comment sections.',
    nameKey: 'habitTemplates.wisdom_bad_9.name',
    descriptionKey: 'habitTemplates.wisdom_bad_9.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'forum',
    color: '#5C6BC0',
    type: 'BAD',
  },
  {
    id: 'wisdom_bad_10',
    name: 'YouTube Binge',
    description: 'Spent a long time watching online videos.',
    nameKey: 'habitTemplates.wisdom_bad_10.name',
    descriptionKey: 'habitTemplates.wisdom_bad_10.description',
    category: 'cat2',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'ondemand-video',
    color: '#26A69A',
    type: 'BAD',
  },

  /* ──────────── HARMONY ──────────── */
  {
    id: 'harmony_good_1',
    name: 'Family Time',
    description: 'Spend quality time with family.',
    nameKey: 'habitTemplates.harmony_good_1.name',
    descriptionKey: 'habitTemplates.harmony_good_1.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'groups',
    color: '#FFB300',
    type: 'GOOD',
  },
  {
    id: 'harmony_good_2',
    name: 'Reach Out to a Friend',
    description: 'Call or message a friend to catch up.',
    nameKey: 'habitTemplates.harmony_good_2.name',
    descriptionKey: 'habitTemplates.harmony_good_2.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'chat',
    color: '#59B0F6',
    type: 'GOOD',
  },
  {
    id: 'harmony_good_3',
    name: 'Random Act of Kindness',
    description: 'Perform a random act of kindness.',
    nameKey: 'habitTemplates.harmony_good_3.name',
    descriptionKey: 'habitTemplates.harmony_good_3.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'volunteer-activism',
    color: '#FF8A65',
    type: 'GOOD',
  },
  {
    id: 'harmony_good_4',
    name: 'Clean Up Space',
    description: 'Tidy your space for 10 minutes.',
    nameKey: 'habitTemplates.harmony_good_4.name',
    descriptionKey: 'habitTemplates.harmony_good_4.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 10,
    defaultGoalUnit: 'minutes',
    icon: 'cleaning-services',
    color: '#26A69A',
    type: 'GOOD',
  },
  {
    id: 'harmony_good_5',
    name: 'Recycling',
    description: 'Properly recycle or sort your waste.',
    nameKey: 'habitTemplates.harmony_good_5.name',
    descriptionKey: 'habitTemplates.harmony_good_5.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'recycling',
    color: '#66BB6A',
    type: 'GOOD',
  },
  {
    id: 'harmony_good_6',
    name: 'Device-Free Hour',
    description: 'Spend one hour without digital devices.',
    nameKey: 'habitTemplates.harmony_good_6.name',
    descriptionKey: 'habitTemplates.harmony_good_6.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 60,
    defaultGoalUnit: 'minutes',
    icon: 'phone-disabled',
    color: '#BA68C8',
    type: 'GOOD',
  },
  {
    id: 'harmony_good_7',
    name: 'Give a Compliment',
    description: 'Give someone a sincere compliment.',
    nameKey: 'habitTemplates.harmony_good_7.name',
    descriptionKey: 'habitTemplates.harmony_good_7.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'thumb-up',
    color: '#FFF176',
    type: 'GOOD',
  },
  {
    id: 'harmony_good_8',
    name: 'Quality Time with Partner',
    description: 'Spend quality time with your partner.',
    nameKey: 'habitTemplates.harmony_good_8.name',
    descriptionKey: 'habitTemplates.harmony_good_8.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'favorite',
    color: '#F48FB1',
    type: 'GOOD',
  },
  {
    id: 'harmony_good_9',
    name: 'Play with Pet',
    description: 'Play with or care for your pet.',
    nameKey: 'habitTemplates.harmony_good_9.name',
    descriptionKey: 'habitTemplates.harmony_good_9.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'pets',
    color: '#4FC3F7',
    type: 'GOOD',
  },
  {
    id: 'harmony_good_10',
    name: 'Express Gratitude',
    description: 'Express or record gratitude.',
    nameKey: 'habitTemplates.harmony_good_10.name',
    descriptionKey: 'habitTemplates.harmony_good_10.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'emoji-emotions',
    color: '#00BCD4',
    type: 'GOOD',
  },

  {
    id: 'harmony_bad_1',
    name: 'Phone at Mealtime',
    description: 'Used phone during meals.',
    nameKey: 'habitTemplates.harmony_bad_1.name',
    descriptionKey: 'habitTemplates.harmony_bad_1.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'smartphone',
    color: '#FFB300',
    type: 'BAD',
  },
  {
    id: 'harmony_bad_2',
    name: 'Skipped Chores',
    description: 'Skipped household chores.',
    nameKey: 'habitTemplates.harmony_bad_2.name',
    descriptionKey: 'habitTemplates.harmony_bad_2.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'weekend',
    color: '#FFB74D',
    type: 'BAD',
  },
  {
    id: 'harmony_bad_3',
    name: 'Road Rage',
    description: 'Lost your temper while driving.',
    nameKey: 'habitTemplates.harmony_bad_3.name',
    descriptionKey: 'habitTemplates.harmony_bad_3.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'directions-car',
    color: '#EF5350',
    type: 'BAD',
  },
  {
    id: 'harmony_bad_4',
    name: 'Ignored Messages',
    description: 'Ignored messages from friends or family.',
    nameKey: 'habitTemplates.harmony_bad_4.name',
    descriptionKey: 'habitTemplates.harmony_bad_4.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'sms-failed',
    color: '#5C6BC0',
    type: 'BAD',
  },
  {
    id: 'harmony_bad_5',
    name: 'Gossiping',
    description: 'Engaged in gossip or negative talk.',
    nameKey: 'habitTemplates.harmony_bad_5.name',
    descriptionKey: 'habitTemplates.harmony_bad_5.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'campaign',
    color: '#F48FB1',
    type: 'BAD',
  },
  {
    id: 'harmony_bad_6',
    name: 'Online Arguments',
    description: 'Argued on the internet.',
    nameKey: 'habitTemplates.harmony_bad_6.name',
    descriptionKey: 'habitTemplates.harmony_bad_6.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'question-answer',
    color: '#7E57C2',
    type: 'BAD',
  },
  {
    id: 'harmony_bad_7',
    name: 'Littering',
    description: 'Littered or failed to dispose of trash responsibly.',
    nameKey: 'habitTemplates.harmony_bad_7.name',
    descriptionKey: 'habitTemplates.harmony_bad_7.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'delete',
    color: '#FF8A65',
    type: 'BAD',
  },
  {
    id: 'harmony_bad_8',
    name: 'Being Late',
    description: 'Arrived late to an appointment or meeting.',
    nameKey: 'habitTemplates.harmony_bad_8.name',
    descriptionKey: 'habitTemplates.harmony_bad_8.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'watch-later',
    color: '#FFF176',
    type: 'BAD',
  },
  {
    id: 'harmony_bad_9',
    name: 'Neglected Partner',
    description: 'Neglected to give partner attention.',
    nameKey: 'habitTemplates.harmony_bad_9.name',
    descriptionKey: 'habitTemplates.harmony_bad_9.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'heart-broken',
    color: '#00BCD4',
    type: 'BAD',
  },
  {
    id: 'harmony_bad_10',
    name: 'Interrupting Others',
    description: 'Interrupted someone while they were speaking.',
    nameKey: 'habitTemplates.harmony_bad_10.name',
    descriptionKey: 'habitTemplates.harmony_bad_10.description',
    category: 'cat3',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'voice-over-off',
    color: '#BA68C8',
    type: 'BAD',
  },

  /* ──────────── SPIRIT ──────────── */
  {
    id: 'spirit_good_1',
    name: 'Meditation',
    description: 'Meditate for 10 minutes.',
    nameKey: 'habitTemplates.spirit_good_1.name',
    descriptionKey: 'habitTemplates.spirit_good_1.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 10,
    defaultGoalUnit: 'minutes',
    icon: 'self-improvement',
    color: '#7E57C2',
    type: 'GOOD',
  },
  {
    id: 'spirit_good_2',
    name: 'Journaling',
    description: 'Write in a journal to reflect.',
    nameKey: 'habitTemplates.spirit_good_2.name',
    descriptionKey: 'habitTemplates.spirit_good_2.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'note-alt',
    color: '#26A69A',
    type: 'GOOD',
  },
  {
    id: 'spirit_good_3',
    name: 'Gratitude Journal',
    description: 'List things you are grateful for.',
    nameKey: 'habitTemplates.spirit_good_3.name',
    descriptionKey: 'habitTemplates.spirit_good_3.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'favorite-border',
    color: '#F48FB1',
    type: 'GOOD',
  },
  {
    id: 'spirit_good_4',
    name: 'Prayer',
    description: 'Spend time in prayer or spiritual reflection.',
    nameKey: 'habitTemplates.spirit_good_4.name',
    descriptionKey: 'habitTemplates.spirit_good_4.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'emoji-people',
    color: '#BA68C8',
    type: 'GOOD',
  },
  {
    id: 'spirit_good_5',
    name: 'Deep Breathing',
    description: 'Do deep-breathing exercises for 5 minutes.',
    nameKey: 'habitTemplates.spirit_good_5.name',
    descriptionKey: 'habitTemplates.spirit_good_5.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 5,
    defaultGoalUnit: 'minutes',
    icon: 'air',
    color: '#4FC3F7',
    type: 'GOOD',
  },
  {
    id: 'spirit_good_6',
    name: 'Positive Affirmations',
    description: 'Recite positive affirmations.',
    nameKey: 'habitTemplates.spirit_good_6.name',
    descriptionKey: 'habitTemplates.spirit_good_6.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'record-voice-over',
    color: '#FFF176',
    type: 'GOOD',
  },
  {
    id: 'spirit_good_7',
    name: 'Read Inspiration',
    description: 'Read an inspirational passage.',
    nameKey: 'habitTemplates.spirit_good_7.name',
    descriptionKey: 'habitTemplates.spirit_good_7.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'auto-stories',
    color: '#81C784',
    type: 'GOOD',
  },
  {
    id: 'spirit_good_8',
    name: 'Self-Reflection',
    description: 'Spend 10 minutes in quiet reflection.',
    nameKey: 'habitTemplates.spirit_good_8.name',
    descriptionKey: 'habitTemplates.spirit_good_8.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 10,
    defaultGoalUnit: 'minutes',
    icon: 'psychology',
    color: '#5C6BC0',
    type: 'GOOD',
  },
  {
    id: 'spirit_good_9',
    name: 'Time in Nature',
    description: 'Spend time outdoors in nature.',
    nameKey: 'habitTemplates.spirit_good_9.name',
    descriptionKey: 'habitTemplates.spirit_good_9.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'park',
    color: '#66BB6A',
    type: 'GOOD',
  },
  {
    id: 'spirit_good_10',
    name: 'Creative Expression',
    description: 'Do something creative for enjoyment.',
    nameKey: 'habitTemplates.spirit_good_10.name',
    descriptionKey: 'habitTemplates.spirit_good_10.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'palette',
    color: '#FF8A65',
    type: 'GOOD',
  },

  {
    id: 'spirit_bad_1',
    name: 'Negative Self-Talk',
    description: 'Engaged in negative self-talk.',
    nameKey: 'habitTemplates.spirit_bad_1.name',
    descriptionKey: 'habitTemplates.spirit_bad_1.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'mood-bad',
    color: '#EF5350',
    type: 'BAD',
  },
  {
    id: 'spirit_bad_2',
    name: 'Anger Outburst',
    description: 'Had an anger outburst.',
    nameKey: 'habitTemplates.spirit_bad_2.name',
    descriptionKey: 'habitTemplates.spirit_bad_2.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'whatshot',
    color: '#FF8A65',
    type: 'BAD',
  },
  {
    id: 'spirit_bad_3',
    name: 'Complaining',
    description: 'Complained excessively.',
    nameKey: 'habitTemplates.spirit_bad_3.name',
    descriptionKey: 'habitTemplates.spirit_bad_3.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'thumb-down',
    color: '#FFB74D',
    type: 'BAD',
  },
  {
    id: 'spirit_bad_4',
    name: 'Holding a Grudge',
    description: 'Held onto resentment.',
    nameKey: 'habitTemplates.spirit_bad_4.name',
    descriptionKey: 'habitTemplates.spirit_bad_4.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'sentiment-very-dissatisfied',
    color: '#5C6BC0',
    type: 'BAD',
  },
  {
    id: 'spirit_bad_5',
    name: 'Overthinking',
    description: 'Over-analyzed or worried excessively.',
    nameKey: 'habitTemplates.spirit_bad_5.name',
    descriptionKey: 'habitTemplates.spirit_bad_5.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'loop',
    color: '#00BCD4',
    type: 'BAD',
  },
  {
    id: 'spirit_bad_6',
    name: 'Comparing Yourself',
    description: 'Compared yourself negatively to others.',
    nameKey: 'habitTemplates.spirit_bad_6.name',
    descriptionKey: 'habitTemplates.spirit_bad_6.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'compare',
    color: '#F48FB1',
    type: 'BAD',
  },
  {
    id: 'spirit_bad_7',
    name: 'Perfectionism',
    description: 'Felt driven by unhealthy perfectionism.',
    nameKey: 'habitTemplates.spirit_bad_7.name',
    descriptionKey: 'habitTemplates.spirit_bad_7.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'star-outline',
    color: '#FFF176',
    type: 'BAD',
  },
  {
    id: 'spirit_bad_8',
    name: 'Judging Others',
    description: 'Judged or criticized others.',
    nameKey: 'habitTemplates.spirit_bad_8.name',
    descriptionKey: 'habitTemplates.spirit_bad_8.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'gavel',
    color: '#BA68C8',
    type: 'BAD',
  },
  {
    id: 'spirit_bad_9',
    name: 'People Pleasing',
    description: "Put others' needs above your own to your detriment.",
    nameKey: 'habitTemplates.spirit_bad_9.name',
    descriptionKey: 'habitTemplates.spirit_bad_9.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'mood',
    color: '#81C784',
    type: 'BAD',
  },
  {
    id: 'spirit_bad_10',
    name: 'Self-Neglect',
    description: 'Neglected personal self-care.',
    nameKey: 'habitTemplates.spirit_bad_10.name',
    descriptionKey: 'habitTemplates.spirit_bad_10.description',
    category: 'cat4',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'battery-alert',
    color: '#FFB300',
    type: 'BAD',
  },

  /* ──────────── AMBITION ──────────── */
  {
    id: 'ambition_good_1',
    name: 'Wake Up Early',
    description: 'Wake up by 7 AM.',
    nameKey: 'habitTemplates.ambition_good_1.name',
    descriptionKey: 'habitTemplates.ambition_good_1.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'time',
    icon: 'alarm',
    color: '#FFB300',
    type: 'GOOD',
  },
  {
    id: 'ambition_good_2',
    name: 'Side-Project Work',
    description: 'Work on a personal project for 60 minutes.',
    nameKey: 'habitTemplates.ambition_good_2.name',
    descriptionKey: 'habitTemplates.ambition_good_2.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 60,
    defaultGoalUnit: 'minutes',
    icon: 'rocket-launch',
    color: '#00BCD4',
    type: 'GOOD',
  },
  {
    id: 'ambition_good_3',
    name: 'Daily Planning',
    description: 'Plan your day in the morning.',
    nameKey: 'habitTemplates.ambition_good_3.name',
    descriptionKey: 'habitTemplates.ambition_good_3.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'task',
    color: '#4FC3F7',
    type: 'GOOD',
  },
  {
    id: 'ambition_good_4',
    name: 'Focused Work',
    description: 'Complete one 25-minute deep-work session.',
    nameKey: 'habitTemplates.ambition_good_4.name',
    descriptionKey: 'habitTemplates.ambition_good_4.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'duration',
    defaultGoalValue: 25,
    defaultGoalUnit: 'minutes',
    icon: 'timer',
    color: '#5C6BC0',
    type: 'GOOD',
  },
  {
    id: 'ambition_good_5',
    name: 'Professional Development',
    description: 'Learn something that advances your career.',
    nameKey: 'habitTemplates.ambition_good_5.name',
    descriptionKey: 'habitTemplates.ambition_good_5.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'work',
    color: '#7E57C2',
    type: 'GOOD',
  },
  {
    id: 'ambition_good_6',
    name: 'Networking',
    description: 'Connect with a colleague or professional contact.',
    nameKey: 'habitTemplates.ambition_good_6.name',
    descriptionKey: 'habitTemplates.ambition_good_6.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'handshake',
    color: '#26A69A',
    type: 'GOOD',
  },
  {
    id: 'ambition_good_7',
    name: 'Save Money',
    description: 'Save $10 toward your goals.',
    nameKey: 'habitTemplates.ambition_good_7.name',
    descriptionKey: 'habitTemplates.ambition_good_7.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'count',
    defaultGoalValue: 10,
    defaultGoalUnit: 'dollars',
    icon: 'savings',
    color: '#66BB6A',
    type: 'GOOD',
  },
  {
    id: 'ambition_good_8',
    name: 'Clear Inbox',
    description: 'Achieve or maintain Inbox Zero.',
    nameKey: 'habitTemplates.ambition_good_8.name',
    descriptionKey: 'habitTemplates.ambition_good_8.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'inbox',
    color: '#81C784',
    type: 'GOOD',
  },
  {
    id: 'ambition_good_9',
    name: 'Track Expenses',
    description: 'Log your daily expenses.',
    nameKey: 'habitTemplates.ambition_good_9.name',
    descriptionKey: 'habitTemplates.ambition_good_9.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'attach-money',
    color: '#FFF176',
    type: 'GOOD',
  },
  {
    id: 'ambition_good_10',
    name: 'Time Tracking',
    description: 'Track how you spend your time today.',
    nameKey: 'habitTemplates.ambition_good_10.name',
    descriptionKey: 'habitTemplates.ambition_good_10.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'pie-chart',
    color: '#FF8A65',
    type: 'GOOD',
  },

  {
    id: 'ambition_bad_1',
    name: 'Procrastination',
    description: 'Procrastinated on important tasks.',
    nameKey: 'habitTemplates.ambition_bad_1.name',
    descriptionKey: 'habitTemplates.ambition_bad_1.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'pending-actions',
    color: '#FF8A65',
    type: 'BAD',
  },
  {
    id: 'ambition_bad_2',
    name: 'Tardiness',
    description: 'Arrived late to work or meetings.',
    nameKey: 'habitTemplates.ambition_bad_2.name',
    descriptionKey: 'habitTemplates.ambition_bad_2.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'timer-off',
    color: '#FFB300',
    type: 'BAD',
  },
  {
    id: 'ambition_bad_3',
    name: 'Overspending',
    description: 'Made unnecessary or impulsive purchases.',
    nameKey: 'habitTemplates.ambition_bad_3.name',
    descriptionKey: 'habitTemplates.ambition_bad_3.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'shopping-cart',
    color: '#EF5350',
    type: 'BAD',
  },
  {
    id: 'ambition_bad_4',
    name: 'Unproductive Day',
    description: 'Felt the day was unproductive.',
    nameKey: 'habitTemplates.ambition_bad_4.name',
    descriptionKey: 'habitTemplates.ambition_bad_4.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'event-busy',
    color: '#4FC3F7',
    type: 'BAD',
  },
  {
    id: 'ambition_bad_5',
    name: 'Skipped Budgeting',
    description: 'Neglected to track expenses or stick to budget.',
    nameKey: 'habitTemplates.ambition_bad_5.name',
    descriptionKey: 'habitTemplates.ambition_bad_5.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'money-off',
    color: '#F48FB1',
    type: 'BAD',
  },
  {
    id: 'ambition_bad_6',
    name: 'Overworking Late',
    description: 'Worked late into the night without rest.',
    nameKey: 'habitTemplates.ambition_bad_6.name',
    descriptionKey: 'habitTemplates.ambition_bad_6.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'work-off',
    color: '#5C6BC0',
    type: 'BAD',
  },
  {
    id: 'ambition_bad_7',
    name: 'Missed Deadline',
    description: 'Missed a project deadline.',
    nameKey: 'habitTemplates.ambition_bad_7.name',
    descriptionKey: 'habitTemplates.ambition_bad_7.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'assignment-late',
    color: '#FFB74D',
    type: 'BAD',
  },
  {
    id: 'ambition_bad_8',
    name: 'Impulse Purchase',
    description: 'Made an unplanned impulse purchase.',
    nameKey: 'habitTemplates.ambition_bad_8.name',
    descriptionKey: 'habitTemplates.ambition_bad_8.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'shopping-bag',
    color: '#FFF176',
    type: 'BAD',
  },
  {
    id: 'ambition_bad_9',
    name: 'Neglected Goals',
    description: 'Failed to work on personal goals.',
    nameKey: 'habitTemplates.ambition_bad_9.name',
    descriptionKey: 'habitTemplates.ambition_bad_9.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'flag',
    color: '#BA68C8',
    type: 'BAD',
  },
  {
    id: 'ambition_bad_10',
    name: 'Skipped Lunch',
    description: 'Skipped lunch or worked through lunch break.',
    nameKey: 'habitTemplates.ambition_bad_10.name',
    descriptionKey: 'habitTemplates.ambition_bad_10.description',
    category: 'cat5',
    frequency: 'daily',
    goalType: 'completion',
    icon: 'no-food',
    color: '#00BCD4',
    type: 'BAD',
  },
];
